# "window.opacity" = 1.0

[colors]
draw_bold_text_with_bright_colors = false

[colors.bright]
black = "#504945"
blue = "#83a598"
cyan = "#8ec07c"
green = "#b8bb26"
magenta = "#d3869b"
red = "#fb4934"
white = "#f9f5d7"
yellow = "#fabd2f"

[colors.cursor]
cursor = "#98971a"

[colors.dim]
black = "#928374"
blue = "#076678"
cyan = "#427b58"
green = "#79740e"
magenta = "#8f3f71"
red = "#9d0006"
white = "#d5c4a1"
yellow = "#b57614"

[colors.normal]
black = "#1d2021"
blue = "#458588"
cyan = "#689d6a"
green = "#98971a"
magenta = "#b16286"
red = "#cc241d"
white = "#ebdbb2"
yellow = "#d79921"

[colors.primary]
background = "#1d2021"
foreground = "#fbf1c7"

[font]
size = 10.5

[font.bold]
family = "Iosevka NFM"
style = "Bold"

[font.italic]
family = "Iosevka NFM"
style = "Italic"

[font.normal]
family = "Iosevka NFM"
style = "regular"

[mouse]
hide_when_typing = false

[[mouse.bindings]]
action = "PasteSelection"
mouse = "Middle"

# [mouse.double_click]
# threshold = 300

# [mouse.triple_click]
# threshold = 300

[scrolling]
history = 10000
multiplier = 3

[window]
dynamic_title = true
