#+title: Modules
#+author: Alsai Samo (imikoy)

* Overview
+ =modules= contains modules, which provide options under common prefix =hlk=.
  + =hardware-traits= contains modules that are applicable to machines with some traits, such as:
    - Having a battery
    - Having a NVIDIA chip
    - Having NVIDIA + AMD chips
    - etc.
    It is currently unpopulated because I have two devices, making it easier to manage them directly.
  + =util= contains modules that are used (almost) exclusively as denpendencies of other modules.
  + =nixos= contains hardware-agnostic modules of NixOS, such as:
    - Basic CLI environment
    - Basic GUI environment
    - Default audio configuration
    - etc.
  + =home-manager= contains modules for home-manager.
+ =machines= contains NixOS configurations.
+ =users= contains home-manager configurations.
+ =dotfiles= contains configuration files for user's environment.
+ =secret.nix= and =secrets= are encrypted in the repository and contain secret information, such as:
  - SSH keys
  - Timezone
  - Machine configuration parts
  - User environment configuration parts
  - etc.
+ =volatile.nix= contains information that is expected to change, such as partition UUIDs.
