#+title: Readme
#+author: Alsai Samo (imikoy)

* Overview
+ =modules= contains modules, which provide options under common prefix =hlk=.
  + =hardware-traits= contains modules that are applicable to machines with some traits, such as:
    - Having a battery
    - Having a NVIDIA chip
    - Having NVIDIA + AMD chips
    - etc.
    It is currently unpopulated because I have two devices, making it easier to manage them directly.
  + =util= contains modules that are used (almost) exclusively as denpendencies of other modules.
  + =nixos= contains hardware-agnostic modules of NixOS, such as:
    - Basic CLI environment
    - Basic GUI environment
    - Default audio configuration
    - etc.
  + =home-manager= contains modules for home-manager.
+ =machines= contains NixOS configurations.
+ =users= contains home-manager configurations.
+ =dotfiles= contains configuration files for user's environment.
+ =secret.nix= and =secrets= are encrypted in the repository and contain secret information, such as:
  - SSH keys
  - Timezone
  - Machine configuration parts
  - User environment configuration parts
  - etc.
+ =volatile.nix= contains information that is expected to change, such as partition UUIDs.
* Filesystem
The filesystem is ZFS. It needs to be set up before installation.
** Structure
1. nix_pool
   1. local
      1. home
         home@blank contains user directories, owned by the respective users, ~Downloads~ and ~large_items~ symlinks to ~../../local_state/home/<username>/<source_dir>~
      2. log
      3. nix
      4. root
         root@blank contains nothing
      5. local_state
   2. safe
      1. secrets
      2. state
