# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.luks.devices = {
    cryptroot = {
      device = "/dev/disk/by-uuid/5b59dbba-ef88-4d00-81b8-9336d7ee3760";
    };
  };

  boot.loader.efi.canTouchEfiVariables  = true;
  boot.loader.grub = {
    enable = true;
    efiSupport = true;
    version = 2;
    enableCryptodisk = true;
    device = "nodev";
  };
  zramSwap.enable = true;

  boot.initrd.availableKernelModules = [ "xhci_pci" "ahci" "ehci_pci" "nvme" "usbhid" "usb_storage" "sd_mod" "rtsx_pci_sdmmc" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" "amdgpu" "acpi_call" ];
  boot.extraModulePackages = with config.boot.kernelPackages; [
    acpi_call
  ];
  boot.kernelParams = ["i8042.nomux=1" "i8042.reset"];

  fileSystems."/" =
    { device = "none";
      fsType = "tmpfs";
#TODO upgrade memory and increase this to 2G
      options = ["defaults" "size=2G" "mode=755"];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/52F6-DE35";
      fsType = "vfat";
    };

  fileSystems."/home" =
    { device = "nix_pool/local/home_tmp";
      fsType = "zfs";
    };
  boot.initrd.postDeviceCommands = lib.mkAfter ''
    zfs rollback -r nix_pool/local/home_tmp@blank
  '';

  fileSystems."/var/log" =
    { device = "nix_pool/local/log";
      fsType = "zfs";
    };

  fileSystems."/nix" =
    { device = "nix_pool/local/nix";
      fsType = "zfs";
    };

  fileSystems."/state" =
    { device = "nix_pool/safe/state";
      fsType = "zfs";
      neededForBoot = true;
    };

  fileSystems."/state/secrets" =
    { device = "nix_pool/safe/secrets";
      fsType = "zfs";
      neededForBoot = true;
    };

  swapDevices = [
  {device ="/dev/nvme1n1p2";
  }];

  services.tlp.enable = true;

  # Enables DHCP on each ethernet and wireless interface. In case of scripted networking
  # (the default) this is the recommended approach. When using systemd-networkd it's
  # still possible to use this option, but it's recommended to use it in conjunction
  # with explicit per-interface declarations with `networking.interfaces.<interface>.useDHCP`.
  networking.useDHCP = lib.mkDefault true;
  # networking.interfaces.enp1s0f0.useDHCP = lib.mkDefault true;
  # networking.interfaces.wlp3s0.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
